create table if not exists public.rsvps (
	id bigint generated by default as identity primary key,
	full_name text not null,
	contact text not null,
	guest_count integer not null check (guest_count between 1 and 20),
	guest_names text,
	message text,
	created_at timestamptz not null default now()
);

alter table public.rsvps enable row level security;

create policy "Anyone can submit an RSVP"
on public.rsvps
for insert
to anon, authenticated
with check (true);
